#!/usr/bin/env bash
# Tells a story based on the contents of the`/etc/passwd` file.

   IFS=:
   while read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOME CMD
   do
	echo "The user $USERNAME is part of the $GROUPID gang, live in $HOME an rides $CMD. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $USERIDINFO"
done < /etc/passwd	
