#!/usr/bin/env bash
#iteration loop

hours=0
minutes=1
while [ $hours -ne 12 ]
do
   echo "Hour: $hour"
   (( minute=1 ))
while [ $minutes -lt 60 ]
do
   echo "$minutes"
   (( minutes++ ))
 done
  (( hour++ ))
done
