#!/usr/bin/env bash
#iteration loop
hour=0
while [ $hours -le 12 ]
do
   echo "Hour: $hour"
     minute=1 
while [ $minutes -lt 60 ]
do
   echo "$minutes"
   (( minutes++ ))
 done
  (( hour++ ))
done
