#!/usr/bin/env bash
# Bash script manages manage_my_process.

PIDFILE="/var/run/my_process.pid"

Error () {
	echo "Usage: manage_my_process {start|stop|restart}"
}

start() {
	./manage_my_process &
       	echo $$ > $PIDFILE
}

stop() {
	pkill -f ./"manage_my_process" & sudo rm $PIDFILE
}

restart() {
	stop
	start
}

if [ $# != 1 ]; then
	Error
else
	case "$1" in
		start)
		    start
		    echo "manage_my_process started";;
	    stop)
		stop
	    echo "manage_my_process stopped";;
    restart)
          restart
          echo "manage_my_process restarted";;
  *)
          Error;;
esac
fi

